# Generated by Django 3.2 on 2021-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='price',
        ),
        migrations.AddField(
            model_name='city',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='movie',
            field=models.ManyToManyField(to='bookings.Movie'),
        ),
        migrations.AddField(
            model_name='theater',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
