# Generated by Django 3.2 on 2021-04-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210424_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.city'),
        ),
    ]
