# Generated by Django 3.2 on 2021-04-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seats_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='code',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='shows',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='city',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.shows'),
        ),
        migrations.AddField(
            model_name='booking',
            name='by_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='on_date',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_in_min',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language_avail',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='markup_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='shown_in_theater',
            field=models.ManyToManyField(to='bookings.Theater'),
        ),
        migrations.AddField(
            model_name='seats',
            name='avail_in_shows',
            field=models.ManyToManyField(to='bookings.Shows'),
        ),
        migrations.AddField(
            model_name='seats',
            name='booked_by_cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.customer'),
        ),
        migrations.AddField(
            model_name='seats',
            name='booking_status',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('NOT_AVAILABLE', 'NOT_AVAILABLE')], default='AVAILABLE', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='seats',
            name='seq_code',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='movie_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.movie'),
        ),
        migrations.AddField(
            model_name='theater',
            name='located_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.city'),
        ),
    ]
