# Generated by Django 3.2 on 2021-04-24 15:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    
    dependencies = [
        ('bookings', '0005_auto_20210424_1537'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='Cities',
        ),
        migrations.AlterModelTable(
            name='seats',
            table='Seats',
        ),
        migrations.AlterModelTable(
            name='shows',
            table='Shows',
        ),
    ]
