# Generated by Django 3.2 on 2021-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210424_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='movie_shown',
        ),
        migrations.AddField(
            model_name='shows',
            name='movie_shown',
            field=models.ManyToManyField(to='bookings.Movie'),
        ),
    ]
