# Generated by Django 3.2 on 2021-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20210424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_in_min',
            field=models.CharField(default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language_avail',
            field=models.CharField(default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='', max_length=24, null=True),
        ),
    ]
