# Generated by Django 3.2 on 2021-04-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20210424_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='movie_shown',
        ),
        migrations.AddField(
            model_name='shows',
            name='movie_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.movie'),
        ),
    ]
