# Generated by Django 3.2 on 2021-04-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20210424_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='at_theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.theater'),
        ),
    ]
