# Generated by Django 3.2 on 2021-04-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_seats_at_theater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='at_theater',
            new_name='present_in_theater',
        ),
    ]
