# Generated by Django 3.2 on 2021-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rename_at_theater_seats_present_in_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='seq_code',
        ),
        migrations.AddField(
            model_name='seats',
            name='name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
