# Generated by Django 3.2 on 2021-04-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20210424_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='name',
            new_name='seat_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at_theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.theater'),
        ),
    ]
