# Generated by Django 3.2 on 2021-04-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20210424_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowsFromTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('movie_shown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.movie')),
            ],
            options={
                'db_table': 'ShowsFromTheater',
            },
        ),
    ]
