# Generated by Django 3.2 on 2021-04-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_showsfromtheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsfromtheater',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.theater'),
        ),
    ]
