# Generated by Django 3.2 on 2021-04-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_showsfromtheater_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_at_theater',
        ),
    ]
