# Generated by Django 3.2 on 2021-04-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_remove_booking_booked_at_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='seats_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theater',
            name='service_charges',
            field=models.IntegerField(default=0),
        ),
    ]
