# Generated by Django 3.2 on 2021-04-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20210425_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='avail_in_shows',
        ),
        migrations.AddField(
            model_name='seats',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.shows'),
        ),
        migrations.DeleteModel(
            name='ShowsFromTheater',
        ),
    ]
