# Generated by Django 3.2 on 2021-04-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_rename_present_in_theater_seats_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='theater',
        ),
    ]
