# Generated by Django 3.2 on 2021-04-26 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_seats_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='seat_code',
        ),
        migrations.AlterField(
            model_name='shows',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.theater'),
        ),
    ]
