# Generated by Django 3.2 on 2021-04-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_auto_20210426_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='by_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.customer'),
        ),
    ]
