# Generated by Django 3.2 on 2021-04-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_booking_by_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.shows'),
        ),
    ]
